// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ScoutsAppContext))]
    [Migration("20251110152528_DistritosRamasYGrupos")]
    partial class DistritosRamasYGrupos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ObjetivoUsuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ObjetivoId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UsuarioId", "ObjetivoId");

                    b.HasIndex("ObjetivoId");

                    b.ToTable("ObjetivoUsuario");
                });

            modelBuilder.Entity("PermisoTipo", b =>
                {
                    b.Property<int>("PermisosId")
                        .HasColumnType("integer");

                    b.Property<int>("TiposId")
                        .HasColumnType("integer");

                    b.HasKey("PermisosId", "TiposId");

                    b.HasIndex("TiposId");

                    b.ToTable("PermisosTipo", (string)null);
                });

            modelBuilder.Entity("UnidadUser", b =>
                {
                    b.Property<int>("UnidadesId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("integer");

                    b.HasKey("UnidadesId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("UnidadUsuario", (string)null);
                });

            modelBuilder.Entity("backend.data.models.AreaCrecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AreasCrecimiento");
                });

            modelBuilder.Entity("backend.data.models.Distrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Distritos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Cochabamba"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Pando"
                        });
                });

            modelBuilder.Entity("backend.data.models.EtapaProgresion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EtapasProgresion");
                });

            modelBuilder.Entity("backend.data.models.GrupoScout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistritoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.ToTable("GruposScout");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistritoId = 1,
                            Nombre = "Tunari"
                        },
                        new
                        {
                            Id = 2,
                            DistritoId = 2,
                            Nombre = "Cobija"
                        });
                });

            modelBuilder.Entity("backend.data.models.ObjetivoEducativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaCrecimientoId")
                        .HasColumnType("integer");

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EtapaId")
                        .HasColumnType("integer");

                    b.Property<int>("EtapaProgresionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaCrecimientoId");

                    b.HasIndex("EtapaProgresionId");

                    b.ToTable("ObjetivosEducativos");
                });

            modelBuilder.Entity("backend.data.models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("backend.data.models.Rama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EdadMaxima")
                        .HasColumnType("integer");

                    b.Property<int>("EdadMinima")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ramas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EdadMaxima = 11,
                            EdadMinima = 7,
                            Nombre = "Lobatos"
                        },
                        new
                        {
                            Id = 2,
                            EdadMaxima = 15,
                            EdadMinima = 11,
                            Nombre = "Exploradores"
                        },
                        new
                        {
                            Id = 3,
                            EdadMaxima = 18,
                            EdadMinima = 15,
                            Nombre = "Pioneros"
                        },
                        new
                        {
                            Id = 4,
                            EdadMaxima = 21,
                            EdadMinima = 18,
                            Nombre = "Rovers"
                        });
                });

            modelBuilder.Entity("backend.data.models.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Scout"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Dirigente"
                        });
                });

            modelBuilder.Entity("backend.data.models.Unidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GrupoScoutId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RamaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrupoScoutId");

                    b.HasIndex("RamaId");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("backend.data.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ObjetivoUsuario", b =>
                {
                    b.HasOne("backend.data.models.ObjetivoEducativo", null)
                        .WithMany()
                        .HasForeignKey("ObjetivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.data.models.User", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermisoTipo", b =>
                {
                    b.HasOne("backend.data.models.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.data.models.Tipo", null)
                        .WithMany()
                        .HasForeignKey("TiposId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UnidadUser", b =>
                {
                    b.HasOne("backend.data.models.Unidad", null)
                        .WithMany()
                        .HasForeignKey("UnidadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.data.models.User", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.data.models.GrupoScout", b =>
                {
                    b.HasOne("backend.data.models.Distrito", "Distrito")
                        .WithMany("GruposScout")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("backend.data.models.ObjetivoEducativo", b =>
                {
                    b.HasOne("backend.data.models.AreaCrecimiento", "AreaCrecimiento")
                        .WithMany("ObjetivosEducativos")
                        .HasForeignKey("AreaCrecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.data.models.EtapaProgresion", "EtapaProgresion")
                        .WithMany("ObjetivosEducativos")
                        .HasForeignKey("EtapaProgresionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaCrecimiento");

                    b.Navigation("EtapaProgresion");
                });

            modelBuilder.Entity("backend.data.models.Unidad", b =>
                {
                    b.HasOne("backend.data.models.GrupoScout", "GrupoScout")
                        .WithMany("Unidades")
                        .HasForeignKey("GrupoScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.data.models.Rama", "Rama")
                        .WithMany("Unidades")
                        .HasForeignKey("RamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoScout");

                    b.Navigation("Rama");
                });

            modelBuilder.Entity("backend.data.models.User", b =>
                {
                    b.HasOne("backend.data.models.Tipo", "Tipo")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("backend.data.models.AreaCrecimiento", b =>
                {
                    b.Navigation("ObjetivosEducativos");
                });

            modelBuilder.Entity("backend.data.models.Distrito", b =>
                {
                    b.Navigation("GruposScout");
                });

            modelBuilder.Entity("backend.data.models.EtapaProgresion", b =>
                {
                    b.Navigation("ObjetivosEducativos");
                });

            modelBuilder.Entity("backend.data.models.GrupoScout", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("backend.data.models.Rama", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("backend.data.models.Tipo", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
