// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ScoutsAppContext))]
    partial class ScoutsAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PermisoUser", b =>
                {
                    b.Property<int>("PermisosId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("PermisosId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("PermisosUsers", (string)null);
                });

            modelBuilder.Entity("UnidadUser", b =>
                {
                    b.Property<int>("UnidadesId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("integer");

                    b.HasKey("UnidadesId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("UnidadUsuario", (string)null);
                });

            modelBuilder.Entity("backend.data.models.AreaCrecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("AreasCrecimiento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Corporalidad"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Carácter"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Afectividad"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Sociabilidad"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Espiritualidad"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Creatividad"
                        });
                });

            modelBuilder.Entity("backend.data.models.Distrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("Distritos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Beni"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Chuquisaca"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cochabamba"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "La Paz"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Oruro"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Potosi"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Santa Cruz"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Tarija"
                        });
                });

            modelBuilder.Entity("backend.data.models.EtapaProgresion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("RamaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RamaId");

                    b.ToTable("EtapasProgresion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pata tierna - Saltador",
                            RamaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Rastreador - Cazador",
                            RamaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Pista - Senda",
                            RamaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Rumbo - Travesía",
                            RamaId = 2
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Busqueda - Encuentro - Desafío",
                            RamaId = 3
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Caminante - Aspirante - Rover",
                            RamaId = 4
                        });
                });

            modelBuilder.Entity("backend.data.models.GrupoScout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistritoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.ToTable("GruposScout");
                });

            modelBuilder.Entity("backend.data.models.ObjetivoEducativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaCrecimientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EtapaProgresionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaCrecimientoId");

                    b.HasIndex("EtapaProgresionId");

                    b.ToTable("ObjetivosEducativos");
                });

            modelBuilder.Entity("backend.data.models.ObjetivoUsuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ObjetivoEducativoId")
                        .HasColumnType("integer");

                    b.Property<int?>("DirigenteAproboId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSeleccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId", "ObjetivoEducativoId");

                    b.HasIndex("DirigenteAproboId");

                    b.HasIndex("ObjetivoEducativoId");

                    b.ToTable("ObjetivosUsuario");
                });

            modelBuilder.Entity("backend.data.models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("backend.data.models.Rama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EdadMaxima")
                        .HasColumnType("integer");

                    b.Property<int>("EdadMinima")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Ramas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EdadMaxima = 11,
                            EdadMinima = 7,
                            Nombre = "Lobatos"
                        },
                        new
                        {
                            Id = 2,
                            EdadMaxima = 15,
                            EdadMinima = 11,
                            Nombre = "Exploradores"
                        },
                        new
                        {
                            Id = 3,
                            EdadMaxima = 18,
                            EdadMinima = 15,
                            Nombre = "Pioneros"
                        },
                        new
                        {
                            Id = 4,
                            EdadMaxima = 21,
                            EdadMinima = 18,
                            Nombre = "Rovers"
                        });
                });

            modelBuilder.Entity("backend.data.models.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Scout"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Dirigente"
                        });
                });

            modelBuilder.Entity("backend.data.models.Unidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("GrupoScoutId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("RamaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrupoScoutId");

                    b.HasIndex("RamaId");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("backend.data.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TipoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.data.models.especialidades.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("RamaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RamaId");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("backend.data.models.especialidades.RequisitoEsp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("RequisitosEsp");
                });

            modelBuilder.Entity("backend.data.models.especialidades.RequisitoEspUser", b =>
                {
                    b.Property<int>("RequisitoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("DirigenteAproboId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSeleccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RequisitoId", "UsuarioId");

                    b.HasIndex("DirigenteAproboId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RequisitoEspUsers");
                });

            modelBuilder.Entity("backend.data.models.profile.DiriProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Cargo1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cargo2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ocupacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Profesion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("DiriProfiles");
                });

            modelBuilder.Entity("backend.data.models.profile.ScoutProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("UnidadEducativa")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.HasKey("Id");

                    b.ToTable("ScoutProfiles");
                });

            modelBuilder.Entity("backend.data.models.profile.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Ci")
                        .HasColumnType("integer");

                    b.Property<string>("ComplementoCi")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Telf")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("PermisoUser", b =>
                {
                    b.HasOne("backend.data.models.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.data.models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UnidadUser", b =>
                {
                    b.HasOne("backend.data.models.Unidad", null)
                        .WithMany()
                        .HasForeignKey("UnidadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.data.models.User", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.data.models.EtapaProgresion", b =>
                {
                    b.HasOne("backend.data.models.Rama", "Rama")
                        .WithMany("EtapasProgresion")
                        .HasForeignKey("RamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rama");
                });

            modelBuilder.Entity("backend.data.models.GrupoScout", b =>
                {
                    b.HasOne("backend.data.models.Distrito", "Distrito")
                        .WithMany("GruposScout")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("backend.data.models.ObjetivoEducativo", b =>
                {
                    b.HasOne("backend.data.models.AreaCrecimiento", "AreaCrecimiento")
                        .WithMany("ObjetivosEducativos")
                        .HasForeignKey("AreaCrecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.data.models.EtapaProgresion", "EtapaProgresion")
                        .WithMany("ObjetivosEducativos")
                        .HasForeignKey("EtapaProgresionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaCrecimiento");

                    b.Navigation("EtapaProgresion");
                });

            modelBuilder.Entity("backend.data.models.ObjetivoUsuario", b =>
                {
                    b.HasOne("backend.data.models.User", "DirigenteAprobo")
                        .WithMany()
                        .HasForeignKey("DirigenteAproboId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.data.models.ObjetivoEducativo", "ObjetivoEducativo")
                        .WithMany("UsuariosObjetivo")
                        .HasForeignKey("ObjetivoEducativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.data.models.User", "User")
                        .WithMany("ObjetivosUsuario")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirigenteAprobo");

                    b.Navigation("ObjetivoEducativo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.data.models.Unidad", b =>
                {
                    b.HasOne("backend.data.models.GrupoScout", "GrupoScout")
                        .WithMany("Unidades")
                        .HasForeignKey("GrupoScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.data.models.Rama", "Rama")
                        .WithMany("Unidades")
                        .HasForeignKey("RamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoScout");

                    b.Navigation("Rama");
                });

            modelBuilder.Entity("backend.data.models.User", b =>
                {
                    b.HasOne("backend.data.models.Tipo", "Tipo")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("backend.data.models.especialidades.Especialidad", b =>
                {
                    b.HasOne("backend.data.models.Rama", "Rama")
                        .WithMany()
                        .HasForeignKey("RamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rama");
                });

            modelBuilder.Entity("backend.data.models.especialidades.RequisitoEsp", b =>
                {
                    b.HasOne("backend.data.models.especialidades.Especialidad", "Especialidad")
                        .WithMany("Requisitos")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("backend.data.models.especialidades.RequisitoEspUser", b =>
                {
                    b.HasOne("backend.data.models.User", "DirigenteAprobo")
                        .WithMany()
                        .HasForeignKey("DirigenteAproboId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.data.models.especialidades.RequisitoEsp", "Requisito")
                        .WithMany("RequisitosEspUser")
                        .HasForeignKey("RequisitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.data.models.User", "Usuario")
                        .WithMany("RequisitoEspUser")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirigenteAprobo");

                    b.Navigation("Requisito");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.data.models.profile.DiriProfile", b =>
                {
                    b.HasOne("backend.data.models.profile.UserProfile", "UserProfile")
                        .WithOne("DiriProfile")
                        .HasForeignKey("backend.data.models.profile.DiriProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("backend.data.models.profile.ScoutProfile", b =>
                {
                    b.HasOne("backend.data.models.profile.UserProfile", "UserProfile")
                        .WithOne("ScoutProfile")
                        .HasForeignKey("backend.data.models.profile.ScoutProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("backend.data.models.profile.UserProfile", b =>
                {
                    b.HasOne("backend.data.models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("backend.data.models.profile.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.data.models.AreaCrecimiento", b =>
                {
                    b.Navigation("ObjetivosEducativos");
                });

            modelBuilder.Entity("backend.data.models.Distrito", b =>
                {
                    b.Navigation("GruposScout");
                });

            modelBuilder.Entity("backend.data.models.EtapaProgresion", b =>
                {
                    b.Navigation("ObjetivosEducativos");
                });

            modelBuilder.Entity("backend.data.models.GrupoScout", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("backend.data.models.ObjetivoEducativo", b =>
                {
                    b.Navigation("UsuariosObjetivo");
                });

            modelBuilder.Entity("backend.data.models.Rama", b =>
                {
                    b.Navigation("EtapasProgresion");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("backend.data.models.Tipo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backend.data.models.User", b =>
                {
                    b.Navigation("ObjetivosUsuario");

                    b.Navigation("Profile");

                    b.Navigation("RequisitoEspUser");
                });

            modelBuilder.Entity("backend.data.models.especialidades.Especialidad", b =>
                {
                    b.Navigation("Requisitos");
                });

            modelBuilder.Entity("backend.data.models.especialidades.RequisitoEsp", b =>
                {
                    b.Navigation("RequisitosEspUser");
                });

            modelBuilder.Entity("backend.data.models.profile.UserProfile", b =>
                {
                    b.Navigation("DiriProfile");

                    b.Navigation("ScoutProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
